### ISSUE TITLE
Link to the wikipedia article

### ISSUE THREAD

**Issue by joker314** [bwbw223/TheGame#1]
If you want to make more people lose this mind game, I suggest you link them to the Wikipedia article explaining the game. 👿

**Comment by bwbw223** [comment]
:P yes

**Comment by bwbw223** [comment]
PR?

**Comment by vutondesign** [comment]
I added this in #2

**Comment by vutondesign** [comment]
@bwbw223 This should be closed now I guess, I never noticed how old it was 🎉
